// Generated by wxt
interface ImportMetaEnv {
  readonly BROWSER: string;
  readonly CHROME: boolean;
  readonly COMMAND: "build" | "serve";
  readonly EDGE: boolean;
  readonly ENTRYPOINT: string;
  readonly FIREFOX: boolean;
  readonly MANIFEST_VERSION: 2 | 3;
  readonly OPERA: boolean;
  readonly SAFARI: boolean;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
