/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspaceWorkspaceWorkspaceIdRouteRouteImport } from './routes/_workspace/workspace/$workspaceId/route'
import { Route as WorkspaceWorkspaceWorkspaceIdIndexRouteImport } from './routes/_workspace/workspace/$workspaceId/index'
import { Route as WorkspaceWorkspaceWorkspaceIdTagsRouteImport } from './routes/_workspace/workspace/$workspaceId/tags'
import { Route as WorkspaceWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_workspace/workspace/$workspaceId/settings'
import { Route as WorkspaceWorkspaceWorkspaceIdSearchRouteImport } from './routes/_workspace/workspace/$workspaceId/search'
import { Route as WorkspaceWorkspaceWorkspaceIdChatRouteImport } from './routes/_workspace/workspace/$workspaceId/chat'
import { Route as WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteImport } from './routes/_workspace/workspace/$workspaceId/library/route'
import { Route as WorkspaceWorkspaceWorkspaceIdTagsIndexRouteImport } from './routes/_workspace/workspace/$workspaceId/tags/index'
import { Route as WorkspaceWorkspaceWorkspaceIdLibraryIndexRouteImport } from './routes/_workspace/workspace/$workspaceId/library/index'
import { Route as WorkspaceWorkspaceWorkspaceIdTagsTagNameRouteImport } from './routes/_workspace/workspace/$workspaceId/tags/$tagName'
import { Route as WorkspaceWorkspaceWorkspaceIdResourceResourceIdRouteImport } from './routes/_workspace/workspace/$workspaceId/resource/$resourceId'
import { Route as WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRouteImport } from './routes/_workspace/workspace/$workspaceId/library/collection/$collectionId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceWorkspaceIdRouteRoute =
  WorkspaceWorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdIndexRoute =
  WorkspaceWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdTagsRoute =
  WorkspaceWorkspaceWorkspaceIdTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdSettingsRoute =
  WorkspaceWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdSearchRoute =
  WorkspaceWorkspaceWorkspaceIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdChatRoute =
  WorkspaceWorkspaceWorkspaceIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute =
  WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdTagsIndexRoute =
  WorkspaceWorkspaceWorkspaceIdTagsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdTagsRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute =
  WorkspaceWorkspaceWorkspaceIdLibraryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute =
  WorkspaceWorkspaceWorkspaceIdTagsTagNameRouteImport.update({
    id: '/$tagName',
    path: '/$tagName',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdTagsRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute =
  WorkspaceWorkspaceWorkspaceIdResourceResourceIdRouteImport.update({
    id: '/resource/$resourceId',
    path: '/resource/$resourceId',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute =
  WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRouteImport.update({
    id: '/collection/$collectionId',
    path: '/collection/$collectionId',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/$workspaceId/library': typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren
  '/workspace/$workspaceId/chat': typeof WorkspaceWorkspaceWorkspaceIdChatRoute
  '/workspace/$workspaceId/search': typeof WorkspaceWorkspaceWorkspaceIdSearchRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/tags': typeof WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/resource/$resourceId': typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute
  '/workspace/$workspaceId/tags/$tagName': typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute
  '/workspace/$workspaceId/library/': typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute
  '/workspace/$workspaceId/tags/': typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRoute
  '/workspace/$workspaceId/library/collection/$collectionId': typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/$workspaceId/chat': typeof WorkspaceWorkspaceWorkspaceIdChatRoute
  '/workspace/$workspaceId/search': typeof WorkspaceWorkspaceWorkspaceIdSearchRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/resource/$resourceId': typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute
  '/workspace/$workspaceId/tags/$tagName': typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute
  '/workspace/$workspaceId/library': typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute
  '/workspace/$workspaceId/tags': typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRoute
  '/workspace/$workspaceId/library/collection/$collectionId': typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/_workspace/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_workspace/workspace/$workspaceId/library': typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren
  '/_workspace/workspace/$workspaceId/chat': typeof WorkspaceWorkspaceWorkspaceIdChatRoute
  '/_workspace/workspace/$workspaceId/search': typeof WorkspaceWorkspaceWorkspaceIdSearchRoute
  '/_workspace/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceWorkspaceIdSettingsRoute
  '/_workspace/workspace/$workspaceId/tags': typeof WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren
  '/_workspace/workspace/$workspaceId/': typeof WorkspaceWorkspaceWorkspaceIdIndexRoute
  '/_workspace/workspace/$workspaceId/resource/$resourceId': typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute
  '/_workspace/workspace/$workspaceId/tags/$tagName': typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute
  '/_workspace/workspace/$workspaceId/library/': typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute
  '/_workspace/workspace/$workspaceId/tags/': typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRoute
  '/_workspace/workspace/$workspaceId/library/collection/$collectionId': typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/chat'
    | '/workspace/$workspaceId'
    | '/api/auth/$'
    | '/workspace/$workspaceId/library'
    | '/workspace/$workspaceId/chat'
    | '/workspace/$workspaceId/search'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/tags'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/resource/$resourceId'
    | '/workspace/$workspaceId/tags/$tagName'
    | '/workspace/$workspaceId/library/'
    | '/workspace/$workspaceId/tags/'
    | '/workspace/$workspaceId/library/collection/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/chat'
    | '/api/auth/$'
    | '/workspace/$workspaceId/chat'
    | '/workspace/$workspaceId/search'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/resource/$resourceId'
    | '/workspace/$workspaceId/tags/$tagName'
    | '/workspace/$workspaceId/library'
    | '/workspace/$workspaceId/tags'
    | '/workspace/$workspaceId/library/collection/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_workspace'
    | '/_auth/login'
    | '/_auth/register'
    | '/api/chat'
    | '/_workspace/workspace/$workspaceId'
    | '/api/auth/$'
    | '/_workspace/workspace/$workspaceId/library'
    | '/_workspace/workspace/$workspaceId/chat'
    | '/_workspace/workspace/$workspaceId/search'
    | '/_workspace/workspace/$workspaceId/settings'
    | '/_workspace/workspace/$workspaceId/tags'
    | '/_workspace/workspace/$workspaceId/'
    | '/_workspace/workspace/$workspaceId/resource/$resourceId'
    | '/_workspace/workspace/$workspaceId/tags/$tagName'
    | '/_workspace/workspace/$workspaceId/library/'
    | '/_workspace/workspace/$workspaceId/tags/'
    | '/_workspace/workspace/$workspaceId/library/collection/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/workspace/$workspaceId': {
      id: '/_workspace/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/$workspaceId/': {
      id: '/_workspace/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/tags': {
      id: '/_workspace/workspace/$workspaceId/tags'
      path: '/tags'
      fullPath: '/workspace/$workspaceId/tags'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/settings': {
      id: '/_workspace/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/search': {
      id: '/_workspace/workspace/$workspaceId/search'
      path: '/search'
      fullPath: '/workspace/$workspaceId/search'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdSearchRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/chat': {
      id: '/_workspace/workspace/$workspaceId/chat'
      path: '/chat'
      fullPath: '/workspace/$workspaceId/chat'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdChatRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/library': {
      id: '/_workspace/workspace/$workspaceId/library'
      path: '/library'
      fullPath: '/workspace/$workspaceId/library'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/tags/': {
      id: '/_workspace/workspace/$workspaceId/tags/'
      path: '/'
      fullPath: '/workspace/$workspaceId/tags/'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsRoute
    }
    '/_workspace/workspace/$workspaceId/library/': {
      id: '/_workspace/workspace/$workspaceId/library/'
      path: '/'
      fullPath: '/workspace/$workspaceId/library/'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute
    }
    '/_workspace/workspace/$workspaceId/tags/$tagName': {
      id: '/_workspace/workspace/$workspaceId/tags/$tagName'
      path: '/$tagName'
      fullPath: '/workspace/$workspaceId/tags/$tagName'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsRoute
    }
    '/_workspace/workspace/$workspaceId/resource/$resourceId': {
      id: '/_workspace/workspace/$workspaceId/resource/$resourceId'
      path: '/resource/$resourceId'
      fullPath: '/workspace/$workspaceId/resource/$resourceId'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/library/collection/$collectionId': {
      id: '/_workspace/workspace/$workspaceId/library/collection/$collectionId'
      path: '/collection/$collectionId'
      fullPath: '/workspace/$workspaceId/library/collection/$collectionId'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteChildren {
  WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute
  WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute
}

const WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteChildren: WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteChildren =
  {
    WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute:
      WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute,
    WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute:
      WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute,
  }

const WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren =
  WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute._addFileChildren(
    WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteChildren,
  )

interface WorkspaceWorkspaceWorkspaceIdTagsRouteChildren {
  WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute
  WorkspaceWorkspaceWorkspaceIdTagsIndexRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRoute
}

const WorkspaceWorkspaceWorkspaceIdTagsRouteChildren: WorkspaceWorkspaceWorkspaceIdTagsRouteChildren =
  {
    WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute:
      WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute,
    WorkspaceWorkspaceWorkspaceIdTagsIndexRoute:
      WorkspaceWorkspaceWorkspaceIdTagsIndexRoute,
  }

const WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren =
  WorkspaceWorkspaceWorkspaceIdTagsRoute._addFileChildren(
    WorkspaceWorkspaceWorkspaceIdTagsRouteChildren,
  )

interface WorkspaceWorkspaceWorkspaceIdRouteRouteChildren {
  WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren
  WorkspaceWorkspaceWorkspaceIdChatRoute: typeof WorkspaceWorkspaceWorkspaceIdChatRoute
  WorkspaceWorkspaceWorkspaceIdSearchRoute: typeof WorkspaceWorkspaceWorkspaceIdSearchRoute
  WorkspaceWorkspaceWorkspaceIdSettingsRoute: typeof WorkspaceWorkspaceWorkspaceIdSettingsRoute
  WorkspaceWorkspaceWorkspaceIdTagsRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren
  WorkspaceWorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceWorkspaceIdIndexRoute
  WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute: typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute
}

const WorkspaceWorkspaceWorkspaceIdRouteRouteChildren: WorkspaceWorkspaceWorkspaceIdRouteRouteChildren =
  {
    WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute:
      WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren,
    WorkspaceWorkspaceWorkspaceIdChatRoute:
      WorkspaceWorkspaceWorkspaceIdChatRoute,
    WorkspaceWorkspaceWorkspaceIdSearchRoute:
      WorkspaceWorkspaceWorkspaceIdSearchRoute,
    WorkspaceWorkspaceWorkspaceIdSettingsRoute:
      WorkspaceWorkspaceWorkspaceIdSettingsRoute,
    WorkspaceWorkspaceWorkspaceIdTagsRoute:
      WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren,
    WorkspaceWorkspaceWorkspaceIdIndexRoute:
      WorkspaceWorkspaceWorkspaceIdIndexRoute,
    WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute:
      WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute,
  }

const WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren =
  WorkspaceWorkspaceWorkspaceIdRouteRoute._addFileChildren(
    WorkspaceWorkspaceWorkspaceIdRouteRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceWorkspaceWorkspaceIdRouteRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceWorkspaceWorkspaceIdRouteRoute:
    WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
