import {
  BookOpenIcon,
  BoxIcon,
  BriefcaseIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  DatabaseIcon,
  FolderIcon,
  GlobeIcon,
  HeartIcon,
  HomeIcon,
  LayersIcon,
  LibraryIcon,
  LightbulbIcon,
  MusicIcon,
  PaletteIcon,
  PenToolIcon,
  RocketIcon,
  SchoolIcon,
  ShieldIcon,
  SparklesIcon,
  StarIcon,
  TargetIcon,
  ZapIcon,
} from "lucide-react";

export const workspaceIcons = [
  { name: "box", icon: BoxIcon },
  { name: "folder", icon: FolderIcon },
  { name: "book", icon: BookOpenIcon },
  { name: "briefcase", icon: BriefcaseIcon },
  { name: "code", icon: CodeIcon },
  { name: "globe", icon: GlobeIcon },
  { name: "home", icon: HomeIcon },
  { name: "layers", icon: LayersIcon },
  { name: "library", icon: LibraryIcon },
  { name: "lightbulb", icon: LightbulbIcon },
  { name: "rocket", icon: RocketIcon },
  { name: "sparkles", icon: SparklesIcon },
  { name: "star", icon: StarIcon },
  { name: "zap", icon: ZapIcon },
  { name: "target", icon: TargetIcon },
  { name: "compass", icon: CompassIcon },
  { name: "palette", icon: PaletteIcon },
  { name: "pen-tool", icon: PenToolIcon },
  { name: "database", icon: DatabaseIcon },
  { name: "shield", icon: ShieldIcon },
  { name: "heart", icon: HeartIcon },
  { name: "coffee", icon: CoffeeIcon },
  { name: "music", icon: MusicIcon },
  { name: "school", icon: SchoolIcon },
] as const;

export type WorkspaceIconName = (typeof workspaceIcons)[number]["name"];

export const getWorkspaceIcon = (name?: string) =>
  workspaceIcons.find((i) => i.name === name)?.icon ?? BoxIcon;
